name: PR and Merge Workflow

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      - auto-test

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install dependencies
        run: |
          cd autotests
          npm ci
          npx playwright install chromium --with-deps
      - name: Run your tests
        run: |
          cd autotests
          xvfb-run --auto-servernum --server-args="-screen 0 1024x768x24" npm test --reporter=html
      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: autotests/playwright-report/
